services:

  data-entry-service:
    build:
      context: .
      dockerfile: src/DataEntryService/Dockerfile
    container_name: data-entry-server
    environment:
      - SESSION_TOKEN=secret
      - COSMOS_CONNECTION_STRING=AccountEndpoint=https://host.docker.internal:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - CosmosDb__ConnectionString=AccountEndpoint=https://host.docker.internal:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - CosmosDb__DatabaseName=resolver_ce
      - CosmosDb__ContainerName=gs1resolver
      - SessionToken__Token=secret
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: always
    networks:
      - resolver-internal-network

  web-service:
    build:
      context: .
      dockerfile: src/WebResolverService/Dockerfile
    container_name: resolver-web-server
    environment:
      - FQDN=id.mydomainname_currently_set_in_dockerfile.com
      - COSMOS_CONNECTION_STRING=AccountEndpoint=https://host.docker.internal:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - CosmosDb__ConnectionString=AccountEndpoint=https://host.docker.internal:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - CosmosDb__DatabaseName=resolver_ce
      - CosmosDb__ContainerName=gs1resolver
      - Fqdn__DomainName=id.mydomainname_currently_set_in_dockerfile.com
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/heartbeat || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: always
    networks:
      - resolver-internal-network

  test-service:
    build:
      context: .
      dockerfile: src/TestHarnessService/Dockerfile
    container_name: test-service
    restart: always
    ports:
      - "4001:5000"
    networks:
      - resolver-internal-network

  frontend-proxy-service:
    build: './proxy'
    container_name: frontend-proxy-server
    depends_on:
      web-service:
        condition: service_healthy
      data-entry-service:
        condition: service_healthy  
    restart: always
    ports:
      - "8080:80"
    networks:
      - resolver-internal-network

networks:
  resolver-internal-network:
    driver: bridge